apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-flask
spec:
  selector:
    app: flask
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 5000
  type: {{ .Values.service.type }}