apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgis
spec:
  selector:
    app: postgis
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 5432
  type: {{ .Values.service.type }}